# Doctor Service Configuration
server:
  port: 8083

spring:
  application:
    name: doctor-service

# Service URLs
service:
  user-data-url: http://user-data-service:8082
  auth-service-url: http://auth-service:8081
